#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        IA_VentilationDeviceServer_01.py
#
#  Project :     IA_VentilationDeviceServer_01
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      a$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["IA_VentilationDeviceServer_01", "IA_VentilationDeviceServer_01Class", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.additionnal_import

# Device States Description
# No states for this device


class IA_VentilationDeviceServer_01 (PyTango.Device_4Impl):
    """Device server representing the PLC 01 managing the datacenter cooling system"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        IA_VentilationDeviceServer_01.init_device(self)
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_temp_01_read = 0.0
        self.attr_temp_03_read = 0.0
        self.attr_temp_05_read = 0.0
        self.attr_temp_07_read = 0.0
        self.attr_temp_09_read = 0.0
        self.attr_temp_11_read = 0.0
        self.attr_hum_01_read = 0.0
        self.attr_hum_03_read = 0.0
        self.attr_hum_05_read = 0.0
        self.attr_hum_07_read = 0.0
        self.attr_hum_09_read = 0.0
        self.attr_hum_11_read = 0.0
        self.attr_air_flow_01_read = 0
        self.attr_fire_00_read = 0
        self.attr_fire_03_read = 0
        self.attr_fire_alarm_read = 0
        self.attr_fan_00_read = 0.0
        self.attr_fan_01_read = 0.0
        self.attr_hum_alarm_read = 0
        self.attr_temp_alarm_read = 0
        self.attr_air_flow_alarm_read = 0
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.always_executed_hook

    # -------------------------------------------------------------------------
    #    IA_VentilationDeviceServer_01 read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_temp_01(self, attr):
        self.debug_stream("In read_temp_01()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_01_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_01 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_01_read = float(content[1])
                print("The temp_01 is ", self.attr_temp_01_read, content[1])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_temp_01_read = 0

        attr.set_value(self.attr_temp_01_read)
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_01_read
        
    def read_temp_03(self, attr):
        self.debug_stream("In read_temp_03()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_03_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_03 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_03_read = float(content[3])
                print("The temp_03 is ", self.attr_temp_03_read, content[3])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_temp_03_read = 0

        attr.set_value(self.attr_temp_03_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_03_read
        
    def read_temp_05(self, attr):
        self.debug_stream("In read_temp_05()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_05_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_05 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_05_read = float(content[5])
                print("The temp_05 is ", self.attr_temp_05_read, content[5])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_temp_05_read = 0

        attr.set_value(self.attr_temp_05_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_05_read
        
    def read_temp_07(self, attr):
        self.debug_stream("In read_temp_07()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_07_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_07 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_07_read = float(content[7])
                print("The temp_07 is ", self.attr_temp_07_read, content[7])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_temp_07_read = 0

        attr.set_value(self.attr_temp_07_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_07_read
        
    def read_temp_09(self, attr):
        self.debug_stream("In read_temp_09()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_09_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_09 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_09_read = float(content[9])
                print("The temp_09 is ", self.attr_temp_09_read, content[9])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_temp_09_read = 0

        attr.set_value(self.attr_temp_09_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_09_read
        
    def read_temp_11(self, attr):
        self.debug_stream("In read_temp_11()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_11_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_11 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_11_read = float(content[11])
                print("The temp_11 is ", self.attr_temp_11_read, content[11])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_temp_11_read = 0

        attr.set_value(self.attr_temp_11_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_11_read
        
    def read_hum_01(self, attr):
        self.debug_stream("In read_hum_01()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_01_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_01 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_01_read = float(content[1])
                print("The hum_01 is ", self.attr_hum_01_read, content[1])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_hum_01_read = 0

        attr.set_value(self.attr_hum_01_read)
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_01_read
        
    def read_hum_03(self, attr):
        self.debug_stream("In read_hum_03()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_03_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_03 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_03_read = float(content[3])
                print("The hum_03 is ", self.attr_hum_03_read, content[3])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_hum_03_read = 0

        attr.set_value(self.attr_hum_03_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_03_read
        
    def read_hum_05(self, attr):
        self.debug_stream("In read_hum_05()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_05_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_05 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_05_read = float(content[5])
                print("The hum_05 is ", self.attr_hum_05_read, content[5])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_hum_05_read = 0

        attr.set_value(self.attr_hum_05_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_05_read
        
    def read_hum_07(self, attr):
        self.debug_stream("In read_hum_07()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_07_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_07 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_07_read = float(content[7])
                print("The hum_07 is ", self.attr_hum_07_read, content[7])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_hum_07_read = 0

        attr.set_value(self.attr_hum_07_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_07_read
        
    def read_hum_09(self, attr):
        self.debug_stream("In read_hum_09()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_09_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_09 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_09_read = float(content[9])
                print("The hum_09 is ", self.attr_hum_09_read, content[9])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_hum_09_read = 0

        attr.set_value(self.attr_hum_09_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_09_read
        
    def read_hum_11(self, attr):
        self.debug_stream("In read_hum_11()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_11_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_11 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_11_read = float(content[11])
                print("The hum_11 is ", self.attr_hum_11_read, content[11])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_hum_11_read = 0

        attr.set_value(self.attr_hum_11_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_11_read
        
    def read_air_flow_01(self, attr):
        self.debug_stream("In read_air_flow_01()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.air_flow_01_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors' 
        print("Reading the air_flow_01 sensor")
        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_air_flow_01_read = float(content[1])
                print("The air_flow_01 is ", self.attr_air_flow_01_read, content[1])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_air_flow_01_read = 0
        attr.set_value(self.attr_air_flow_01_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.air_flow_01_read
        
    def read_fire_00(self, attr):
        self.debug_stream("In read_fire_00()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fire_00_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_fire.sensors' 

        print("Reading the fire_00 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_fire_00_read = int(content[0])
                print("The fire_00 is ", self.attr_fire_00_read, content[0])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_fire_00_read = 0

        attr.set_value(self.attr_fire_00_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fire_00_read
        
    def read_fire_03(self, attr):
        self.debug_stream("In read_fire_03()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fire_03_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_fire.sensors' 

        print("Reading the fire_03 sensors")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_fire_03_read = int(content[3])
                print("The fire_03 is ", self.attr_fire_03_read, content[3])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read sensors from file")
            print("\t", e)
            self.attr_fire_03_read = 0

        attr.set_value(self.attr_fire_03_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fire_03_read
        
    def read_fire_alarm(self, attr):
        self.debug_stream("In read_fire_alarm()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fire_alarm_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_fire.sensors' 

        print("Reading the fire_alarm actuator")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_fire_alarm_read = int(content[4])
                print("The fire_alarm is ", self.attr_fire_alarm_read, content[4])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read actuators from file")
            print("\t", e)
            self.attr_fire_alarm_read = 0

        attr.set_value(self.attr_fire_alarm_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fire_alarm_read
        
    def read_fan_00(self, attr):
        self.debug_stream("In read_fan_00()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fan_00_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors' 

        print("Reading the fan_00 sensor")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_fan_00_read = float(content[3])
                print("The fan_00 is ", self.attr_fan_00_read, content[3])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read actuators from file")
            print("\t", e)
            self.attr_fan_00_read = 0

        attr.set_value(self.attr_fan_00_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fan_00_read
        
    def write_fan_00(self, attr):
        self.debug_stream("In write_fan_00()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fan_00_write) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter.actuators' 

        print("Writing to the fan_00 actuator")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.readlines()
                content[0] = str(float(data)) + '\n'
            with open(COM_FILE_SENSORS, 'w') as f:
                for line in content:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to write fan_00 to file")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fan_00_write
        
    def read_fan_01(self, attr):
        self.debug_stream("In read_fan_01()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fan_01_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors' 

        print("Reading the fan_01 sensor")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_fan_01_read = float(content[4])
                print("The fan_01 is ", self.attr_fan_01_read, content[4])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read actuators from file")
            print("\t", e)
            self.attr_fan_01_read = 0

        attr.set_value(self.attr_fan_01_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fan_01_read
        
    def write_fan_01(self, attr):
        self.debug_stream("In write_fan_01()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.fan_01_write) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter.actuators' 

        print("Writing to the fan_01 actuator")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.readlines()
                content[1] = str(float(data)) + '\n'
            with open(COM_FILE_SENSORS, 'w') as f:
                for line in content:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to write fan_01 to file")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.fan_01_write
        
    def read_hum_alarm(self, attr):
        self.debug_stream("In read_hum_alarm()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.hum_alarm_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_hum.sensors' 

        print("Reading the hum_alarm")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_hum_alarm_read = int(content[12])
                print("The hum_alarm is ", self.attr_hum_alarm_read, content[12])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read hum_alarm from file")
            print("\t", e)
            self.attr_hum_alarm_read = 0

        attr.set_value(self.attr_hum_alarm_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.hum_alarm_read
        
    def read_temp_alarm(self, attr):
        self.debug_stream("In read_temp_alarm()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.temp_alarm_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_temp.sensors' 

        print("Reading the temp_alarm")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_temp_alarm_read = int(content[12])
                print("The temp_alarm is ", self.attr_temp_alarm_read, content[12])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to temp_alarm from file")
            print("\t", e)
            self.attr_temp_alarm_read = 0

        attr.set_value(self.attr_temp_alarm_read)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.temp_alarm_read
        
    def read_air_flow_alarm(self, attr):
        self.debug_stream("In read_air_flow_alarm()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.air_flow_alarm_read) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors' 

        print("Reading the air_flow_alarm")

        try:
            with open(COM_FILE_SENSORS, 'r') as f:
                content = f.read().splitlines()
                self.attr_air_flow_alarm_read = int(content[6])
                print("The air_flow_alarm is ", self.attr_temp_alarm_read, content[6])
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to read air_flow_alarm from file")
            print("\t", e)
            self.attr_air_alarm_read = 0
        attr.set_value(self.attr_air_flow_alarm_read)

        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.air_flow_alarm_read
        
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.read_attr_hardware


    # -------------------------------------------------------------------------
    #    IA_VentilationDeviceServer_01 command methods
    # -------------------------------------------------------------------------
    
    def start(self):
        """ Start the fans at speed 100%
        """
        self.debug_stream("In start()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.start) ENABLED START -----#
        COM_FILE_ACTUATORS = '/tmp/datacenter.actuators'
        print("Start all fans")
        try:
            speed = 100.0
            with open(COM_FILE_ACTUATORS, 'r') as f:
                content = f.readlines()
                content[0] = content[1] = content[2] = str(speed) + '\n'
            with open(COM_FILE_ACTUATORS, 'w') as f:
                for line in content:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to set fan speeds to 100%")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.start
        
    def stop(self):
        """ Stop the fans
        """
        self.debug_stream("In stop()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.stop) ENABLED START -----#
        COM_FILE_ACTUATORS = '/tmp/datacenter.actuators'
        print("Stop all fans")
        try:
            speed = 0.0
            with open(COM_FILE_ACTUATORS, 'r') as f:
                content = f.readlines()
                content[0] = content[1] = content[2] = str(speed) + '\n'
            with open(COM_FILE_ACTUATORS, 'w') as f:
                for line in content:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to set fan speeds to 0%")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.stop
        
    def increase_speed_fan_00(self):
        """ Increase fan_00`s speed by 10%
        """
        self.debug_stream("In increase_speed_fan_00()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.increase_speed_fan_00) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors'
        COM_FILE_ACTUATORS = '/tmp/datacenter.actuators'
        print("Increase fan_00's speed")
        try:
            speed = 0.0
            with open(COM_FILE_SENSORS, 'r') as f:
                content_sensors = f.read().splitlines()
            with open(COM_FILE_ACTUATORS, 'r') as f:
                content_actuators = f.readlines()

            speed = float(content_sensors[3])
            speed = speed + 10 if speed + 10 <= 100 else 100
            content_actuators[0] = str(speed) + '\n'
            
            with open(COM_FILE_ACTUATORS, 'w') as f:
                for line in content_actuators:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to increase fan_00's speed")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.increase_speed_fan_00
        
    def decrease_speed_fan_00(self):
        """ Decrease fan_00`s speed by 10%
        """
        self.debug_stream("In decrease_speed_fan_00()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.decrease_speed_fan_00) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors'
        COM_FILE_ACTUATORS = '/tmp/datacenter.actuators'
        print("Decrease fan_00's speed")
        try:
            speed = 0.0
            with open(COM_FILE_SENSORS, 'r') as f:
                content_sensors = f.read().splitlines()
            with open(COM_FILE_ACTUATORS, 'r') as f:
                content_actuators = f.readlines()

            speed = float(content_sensors[3])
            speed = speed - 10 if speed - 10 >= 0 else 0
            content_actuators[0] = str(speed) + '\n'
            
            with open(COM_FILE_ACTUATORS, 'w') as f:
                for line in content_actuators:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to decrease fan_00's speed")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.decrease_speed_fan_00
        
    def increase_speed_fan_01(self):
        """ Increase fan_01`s speed by 10%
        """
        self.debug_stream("In increase_speed_fan_01()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.increase_speed_fan_01) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors'
        COM_FILE_ACTUATORS = '/tmp/datacenter.actuators'
        print("Increase fan_01's speed")
        try:
            speed = 0.0
            with open(COM_FILE_SENSORS, 'r') as f:
                content_sensors = f.read().splitlines()
            with open(COM_FILE_ACTUATORS, 'r') as f:
                content_actuators = f.readlines()

            speed = float(content_sensors[4])
            speed = speed + 10 if speed + 10 <= 100 else 100
            content_actuators[1] = str(speed) + '\n'
            
            with open(COM_FILE_ACTUATORS, 'w') as f:
                for line in content_actuators:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to increase fan_01's speed")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.increase_speed_fan_01
        
    def decrease_speed_fan_01(self):
        """ Decrease fan_01`s speed by 10%
        """
        self.debug_stream("In decrease_speed_fan_01()")
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.decrease_speed_fan_01) ENABLED START -----#
        COM_FILE_SENSORS = '/tmp/datacenter_air.sensors'
        COM_FILE_ACTUATORS = '/tmp/datacenter.actuators'
        print("Decrease fan_01's speed")
        try:
            speed = 0.0
            with open(COM_FILE_SENSORS, 'r') as f:
                content_sensors = f.read().splitlines()
            with open(COM_FILE_ACTUATORS, 'r') as f:
                content_actuators = f.readlines()

            speed = float(content_sensors[4])
            speed = speed - 10 if speed - 10 >= 0 else 0
            content_actuators[1] = str(speed) + '\n'
            
            with open(COM_FILE_ACTUATORS, 'w') as f:
                for line in content_actuators:
                    f.write(line)
        except (IOError, ValueError, IndexError) as e:
            print("\tUnable to decrease fan_01's speed")
            print("\t", e)
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.decrease_speed_fan_01
        

    #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.programmer_methods

class IA_VentilationDeviceServer_01Class(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'start':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'stop':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'increase_speed_fan_00':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'decrease_speed_fan_00':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'increase_speed_fan_01':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'decrease_speed_fan_01':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'temp_01':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'label': "Temp_1",
                'unit': "Celsius",
                'standard unit': "Celsius",
                'display unit': "C",
            } ],
        'temp_03':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "Celsius",
                'standard unit': "Celsius",
                'display unit': "C",
            } ],
        'temp_05':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "Celsius",
                'standard unit': "Celsius",
                'display unit': "C",
            } ],
        'temp_07':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "Celsius",
                'standard unit': "Celsius",
                'display unit': "C",
            } ],
        'temp_09':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "Celsius",
                'standard unit': "Celsius",
                'display unit': "C",
            } ],
        'temp_11':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "Celsius",
                'standard unit': "Celsius",
                'display unit': "C",
            } ],
        'hum_01':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'standard unit': "%",
                'display unit': "%",
            } ],
        'hum_03':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'standard unit': "%",
                'display unit': "%",
            } ],
        'hum_05':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'standard unit': "%",
                'display unit': "%",
            } ],
        'hum_07':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'standard unit': "%",
                'display unit': "%",
            } ],
        'hum_09':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'standard unit': "%",
                'display unit': "%",
            } ],
        'hum_11':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'standard unit': "%",
                'display unit': "%",
            } ],
        'air_flow_01':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        'fire_00':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        'fire_03':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        'fire_alarm':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        'fan_00':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Polling period': "1000",
            } ],
        'fan_01':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Polling period': "1000",
            } ],
        'hum_alarm':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        'temp_alarm':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        'air_flow_alarm':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(IA_VentilationDeviceServer_01Class, IA_VentilationDeviceServer_01, 'IA_VentilationDeviceServer_01')
        #----- PROTECTED REGION ID(IA_VentilationDeviceServer_01.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	IA_VentilationDeviceServer_01.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
