# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HMI.ui'
#
# Created: Mon May 22 20:52:22 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1703, 942)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.datacenter_ch = QtGui.QFrame(self.centralwidget)
        self.datacenter_ch.setGeometry(QtCore.QRect(0, 0, 821, 801))
        self.datacenter_ch.setFrameShape(QtGui.QFrame.Box)
        self.datacenter_ch.setFrameShadow(QtGui.QFrame.Raised)
        self.datacenter_ch.setLineWidth(2)
        self.datacenter_ch.setObjectName(_fromUtf8("datacenter_ch"))
        self.qPixmapWidget_4 = QPixmapWidget(self.datacenter_ch)
        self.qPixmapWidget_4.setGeometry(QtCore.QRect(10, 80, 391, 331))
        self.qPixmapWidget_4.setPixmap(QtGui.QPixmap(_fromUtf8("images/cern_ch.jpg")))
        self.qPixmapWidget_4.setAspectRatioMode(QtCore.Qt.IgnoreAspectRatio)
        self.qPixmapWidget_4.setObjectName(_fromUtf8("qPixmapWidget_4"))
        self.frame_vent_ch = QtGui.QFrame(self.datacenter_ch)
        self.frame_vent_ch.setGeometry(QtCore.QRect(10, 410, 801, 221))
        self.frame_vent_ch.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_vent_ch.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_vent_ch.setLineWidth(1)
        self.frame_vent_ch.setObjectName(_fromUtf8("frame_vent_ch"))
        self.widget_fan00_ch = QtGui.QWidget(self.frame_vent_ch)
        self.widget_fan00_ch.setGeometry(QtCore.QRect(10, 50, 201, 171))
        self.widget_fan00_ch.setObjectName(_fromUtf8("widget_fan00_ch"))
        self.qPixmapWidget = QPixmapWidget(self.widget_fan00_ch)
        self.qPixmapWidget.setGeometry(QtCore.QRect(50, 10, 111, 101))
        self.qPixmapWidget.setPixmap(QtGui.QPixmap(_fromUtf8("images/fan.png")))
        self.qPixmapWidget.setObjectName(_fromUtf8("qPixmapWidget"))
        self.label = QtGui.QLabel(self.widget_fan00_ch)
        self.label.setGeometry(QtCore.QRect(80, 0, 58, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.taurusLabelEditRW = TaurusLabelEditRW(self.widget_fan00_ch)
        self.taurusLabelEditRW.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.taurusLabelEditRW.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabelEditRW.setObjectName(_fromUtf8("taurusLabelEditRW"))
        self.label_15 = QtGui.QLabel(self.widget_fan00_ch)
        self.label_15.setGeometry(QtCore.QRect(30, 120, 57, 15))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.widget_fan00_ch)
        self.label_16.setGeometry(QtCore.QRect(150, 120, 16, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.widget_fan01_ch = QtGui.QWidget(self.frame_vent_ch)
        self.widget_fan01_ch.setGeometry(QtCore.QRect(200, 50, 191, 171))
        self.widget_fan01_ch.setObjectName(_fromUtf8("widget_fan01_ch"))
        self.qPixmapWidget_2 = QPixmapWidget(self.widget_fan01_ch)
        self.qPixmapWidget_2.setGeometry(QtCore.QRect(50, 10, 111, 101))
        self.qPixmapWidget_2.setPixmap(QtGui.QPixmap(_fromUtf8("images/fan.png")))
        self.qPixmapWidget_2.setObjectName(_fromUtf8("qPixmapWidget_2"))
        self.label_2 = QtGui.QLabel(self.widget_fan01_ch)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 58, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_17 = QtGui.QLabel(self.widget_fan01_ch)
        self.label_17.setGeometry(QtCore.QRect(150, 120, 16, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.taurusLabelEditRW_2 = TaurusLabelEditRW(self.widget_fan01_ch)
        self.taurusLabelEditRW_2.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.taurusLabelEditRW_2.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabelEditRW_2.setObjectName(_fromUtf8("taurusLabelEditRW_2"))
        self.label_18 = QtGui.QLabel(self.widget_fan01_ch)
        self.label_18.setGeometry(QtCore.QRect(30, 120, 57, 15))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.widget_fan02_ch = QtGui.QWidget(self.frame_vent_ch)
        self.widget_fan02_ch.setGeometry(QtCore.QRect(410, 50, 181, 171))
        self.widget_fan02_ch.setObjectName(_fromUtf8("widget_fan02_ch"))
        self.qPixmapWidget_3 = QPixmapWidget(self.widget_fan02_ch)
        self.qPixmapWidget_3.setGeometry(QtCore.QRect(40, 10, 111, 101))
        self.qPixmapWidget_3.setPixmap(QtGui.QPixmap(_fromUtf8("images/fan.png")))
        self.qPixmapWidget_3.setObjectName(_fromUtf8("qPixmapWidget_3"))
        self.label_3 = QtGui.QLabel(self.widget_fan02_ch)
        self.label_3.setGeometry(QtCore.QRect(70, 0, 58, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_20 = QtGui.QLabel(self.widget_fan02_ch)
        self.label_20.setGeometry(QtCore.QRect(30, 120, 57, 15))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_19 = QtGui.QLabel(self.widget_fan02_ch)
        self.label_19.setGeometry(QtCore.QRect(150, 120, 16, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.taurusLabelEditRW_3 = TaurusLabelEditRW(self.widget_fan02_ch)
        self.taurusLabelEditRW_3.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.taurusLabelEditRW_3.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabelEditRW_3.setObjectName(_fromUtf8("taurusLabelEditRW_3"))
        self.taurusCommandButton_7 = TaurusCommandButton(self.frame_vent_ch)
        self.taurusCommandButton_7.setGeometry(QtCore.QRect(610, 80, 121, 25))
        self.taurusCommandButton_7.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.taurusCommandButton_7.setObjectName(_fromUtf8("taurusCommandButton_7"))
        self.taurusCommandButton_8 = TaurusCommandButton(self.frame_vent_ch)
        self.taurusCommandButton_8.setGeometry(QtCore.QRect(610, 150, 121, 25))
        self.taurusCommandButton_8.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.taurusCommandButton_8.setObjectName(_fromUtf8("taurusCommandButton_8"))
        self.label_4 = QtGui.QLabel(self.frame_vent_ch)
        self.label_4.setGeometry(QtCore.QRect(290, 20, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_11 = QtGui.QLabel(self.datacenter_ch)
        self.label_11.setGeometry(QtCore.QRect(430, 130, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.datacenter_ch)
        self.label_12.setGeometry(QtCore.QRect(430, 180, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.taurusLed_3 = TaurusLed(self.datacenter_ch)
        self.taurusLed_3.setGeometry(QtCore.QRect(560, 120, 31, 31))
        self.taurusLed_3.setLedInverted(False)
        self.taurusLed_3.setObjectName(_fromUtf8("taurusLed_3"))
        self.taurusLed_2 = TaurusLed(self.datacenter_ch)
        self.taurusLed_2.setGeometry(QtCore.QRect(560, 170, 31, 31))
        self.taurusLed_2.setLedInverted(False)
        self.taurusLed_2.setObjectName(_fromUtf8("taurusLed_2"))
        self.label_13 = QtGui.QLabel(self.datacenter_ch)
        self.label_13.setGeometry(QtCore.QRect(430, 220, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.taurusLed_4 = TaurusLed(self.datacenter_ch)
        self.taurusLed_4.setGeometry(QtCore.QRect(560, 210, 31, 31))
        self.taurusLed_4.setLedInverted(False)
        self.taurusLed_4.setObjectName(_fromUtf8("taurusLed_4"))
        self.btn_details_ch = QtGui.QPushButton(self.datacenter_ch)
        self.btn_details_ch.setGeometry(QtCore.QRect(490, 330, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_details_ch.setFont(font)
        self.btn_details_ch.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.btn_details_ch.setCheckable(True)
        self.btn_details_ch.setChecked(True)
        self.btn_details_ch.setAutoDefault(False)
        self.btn_details_ch.setObjectName(_fromUtf8("btn_details_ch"))
        self.label_14 = QtGui.QLabel(self.datacenter_ch)
        self.label_14.setGeometry(QtCore.QRect(240, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtGui.QFrame.Box)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.taurusLed = TaurusLed(self.datacenter_ch)
        self.taurusLed.setGeometry(QtCore.QRect(560, 260, 31, 31))
        self.taurusLed.setLedInverted(False)
        self.taurusLed.setObjectName(_fromUtf8("taurusLed"))
        self.label_9 = QtGui.QLabel(self.datacenter_ch)
        self.label_9.setGeometry(QtCore.QRect(430, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.datacenter_ch)
        self.label_8.setGeometry(QtCore.QRect(610, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.datacenter_ch)
        self.label_10.setGeometry(QtCore.QRect(610, 180, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_21 = QtGui.QLabel(self.datacenter_ch)
        self.label_21.setGeometry(QtCore.QRect(610, 270, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.frame_details_ch = TaurusWidget(self.centralwidget)
        self.frame_details_ch.setGeometry(QtCore.QRect(10, 640, 831, 181))
        self.frame_details_ch.setObjectName(_fromUtf8("frame_details_ch"))
        self.air_details_ch = QtGui.QFrame(self.frame_details_ch)
        self.air_details_ch.setGeometry(QtCore.QRect(0, 0, 181, 121))
        self.air_details_ch.setFrameShape(QtGui.QFrame.NoFrame)
        self.air_details_ch.setFrameShadow(QtGui.QFrame.Raised)
        self.air_details_ch.setObjectName(_fromUtf8("air_details_ch"))
        self.taurusLabel_10 = TaurusLabel(self.air_details_ch)
        self.taurusLabel_10.setGeometry(QtCore.QRect(90, 90, 61, 17))
        self.taurusLabel_10.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_10.setPrefixText(_fromUtf8(""))
        self.taurusLabel_10.setObjectName(_fromUtf8("taurusLabel_10"))
        self.label_26 = QtGui.QLabel(self.air_details_ch)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.taurusLabel_11 = TaurusLabel(self.air_details_ch)
        self.taurusLabel_11.setGeometry(QtCore.QRect(90, 60, 61, 17))
        self.taurusLabel_11.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_11.setPrefixText(_fromUtf8(""))
        self.taurusLabel_11.setObjectName(_fromUtf8("taurusLabel_11"))
        self.taurusLabel_12 = TaurusLabel(self.air_details_ch)
        self.taurusLabel_12.setGeometry(QtCore.QRect(90, 30, 61, 17))
        self.taurusLabel_12.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_12.setPrefixText(_fromUtf8(""))
        self.taurusLabel_12.setObjectName(_fromUtf8("taurusLabel_12"))
        self.label_25 = QtGui.QLabel(self.air_details_ch)
        self.label_25.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_27 = QtGui.QLabel(self.air_details_ch)
        self.label_27.setGeometry(QtCore.QRect(20, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.air_details_ch)
        self.label_28.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.temp_details_ch = QtGui.QFrame(self.frame_details_ch)
        self.temp_details_ch.setGeometry(QtCore.QRect(270, 0, 251, 151))
        self.temp_details_ch.setFrameShape(QtGui.QFrame.NoFrame)
        self.temp_details_ch.setFrameShadow(QtGui.QFrame.Raised)
        self.temp_details_ch.setObjectName(_fromUtf8("temp_details_ch"))
        self.label_29 = QtGui.QLabel(self.temp_details_ch)
        self.label_29.setGeometry(QtCore.QRect(50, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.temp_details_ch)
        self.label_30.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.taurusLabel_13 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_13.setGeometry(QtCore.QRect(70, 30, 51, 17))
        self.taurusLabel_13.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_13.setPrefixText(_fromUtf8(""))
        self.taurusLabel_13.setObjectName(_fromUtf8("taurusLabel_13"))
        self.taurusLabel_14 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_14.setGeometry(QtCore.QRect(70, 50, 51, 17))
        self.taurusLabel_14.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_14.setPrefixText(_fromUtf8(""))
        self.taurusLabel_14.setObjectName(_fromUtf8("taurusLabel_14"))
        self.label_31 = QtGui.QLabel(self.temp_details_ch)
        self.label_31.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.taurusLabel_15 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_15.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.taurusLabel_15.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_15.setPrefixText(_fromUtf8(""))
        self.taurusLabel_15.setObjectName(_fromUtf8("taurusLabel_15"))
        self.label_32 = QtGui.QLabel(self.temp_details_ch)
        self.label_32.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.taurusLabel_16 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_16.setGeometry(QtCore.QRect(70, 90, 51, 17))
        self.taurusLabel_16.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_16.setPrefixText(_fromUtf8(""))
        self.taurusLabel_16.setObjectName(_fromUtf8("taurusLabel_16"))
        self.label_33 = QtGui.QLabel(self.temp_details_ch)
        self.label_33.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.taurusLabel_17 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_17.setGeometry(QtCore.QRect(70, 110, 51, 17))
        self.taurusLabel_17.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_17.setPrefixText(_fromUtf8(""))
        self.taurusLabel_17.setObjectName(_fromUtf8("taurusLabel_17"))
        self.label_34 = QtGui.QLabel(self.temp_details_ch)
        self.label_34.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.taurusLabel_18 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_18.setGeometry(QtCore.QRect(70, 130, 51, 17))
        self.taurusLabel_18.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_18.setPrefixText(_fromUtf8(""))
        self.taurusLabel_18.setObjectName(_fromUtf8("taurusLabel_18"))
        self.label_35 = QtGui.QLabel(self.temp_details_ch)
        self.label_35.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.taurusLabel_19 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_19.setGeometry(QtCore.QRect(190, 30, 51, 17))
        self.taurusLabel_19.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_19.setPrefixText(_fromUtf8(""))
        self.taurusLabel_19.setObjectName(_fromUtf8("taurusLabel_19"))
        self.label_36 = QtGui.QLabel(self.temp_details_ch)
        self.label_36.setGeometry(QtCore.QRect(130, 30, 61, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.taurusLabel_20 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_20.setGeometry(QtCore.QRect(190, 50, 51, 17))
        self.taurusLabel_20.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_20.setPrefixText(_fromUtf8(""))
        self.taurusLabel_20.setObjectName(_fromUtf8("taurusLabel_20"))
        self.label_37 = QtGui.QLabel(self.temp_details_ch)
        self.label_37.setGeometry(QtCore.QRect(130, 50, 61, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.taurusLabel_21 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_21.setGeometry(QtCore.QRect(190, 70, 51, 17))
        self.taurusLabel_21.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_21.setPrefixText(_fromUtf8(""))
        self.taurusLabel_21.setObjectName(_fromUtf8("taurusLabel_21"))
        self.label_38 = QtGui.QLabel(self.temp_details_ch)
        self.label_38.setGeometry(QtCore.QRect(130, 70, 61, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.taurusLabel_22 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_22.setGeometry(QtCore.QRect(190, 90, 51, 17))
        self.taurusLabel_22.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_22.setPrefixText(_fromUtf8(""))
        self.taurusLabel_22.setObjectName(_fromUtf8("taurusLabel_22"))
        self.label_39 = QtGui.QLabel(self.temp_details_ch)
        self.label_39.setGeometry(QtCore.QRect(130, 90, 61, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.taurusLabel_23 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_23.setGeometry(QtCore.QRect(190, 110, 51, 17))
        self.taurusLabel_23.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_23.setPrefixText(_fromUtf8(""))
        self.taurusLabel_23.setObjectName(_fromUtf8("taurusLabel_23"))
        self.label_40 = QtGui.QLabel(self.temp_details_ch)
        self.label_40.setGeometry(QtCore.QRect(130, 110, 61, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.taurusLabel_24 = TaurusLabel(self.temp_details_ch)
        self.taurusLabel_24.setGeometry(QtCore.QRect(190, 130, 51, 17))
        self.taurusLabel_24.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_24.setPrefixText(_fromUtf8(""))
        self.taurusLabel_24.setObjectName(_fromUtf8("taurusLabel_24"))
        self.label_41 = QtGui.QLabel(self.temp_details_ch)
        self.label_41.setGeometry(QtCore.QRect(130, 130, 61, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.hum_details_ch = QtGui.QFrame(self.frame_details_ch)
        self.hum_details_ch.setGeometry(QtCore.QRect(520, 0, 281, 151))
        self.hum_details_ch.setFrameShape(QtGui.QFrame.NoFrame)
        self.hum_details_ch.setFrameShadow(QtGui.QFrame.Raised)
        self.hum_details_ch.setObjectName(_fromUtf8("hum_details_ch"))
        self.label_42 = QtGui.QLabel(self.hum_details_ch)
        self.label_42.setGeometry(QtCore.QRect(70, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.hum_details_ch)
        self.label_43.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.taurusLabel_25 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_25.setGeometry(QtCore.QRect(80, 30, 51, 17))
        self.taurusLabel_25.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_25.setPrefixText(_fromUtf8(""))
        self.taurusLabel_25.setObjectName(_fromUtf8("taurusLabel_25"))
        self.taurusLabel_26 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_26.setGeometry(QtCore.QRect(80, 50, 51, 17))
        self.taurusLabel_26.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_26.setPrefixText(_fromUtf8(""))
        self.taurusLabel_26.setObjectName(_fromUtf8("taurusLabel_26"))
        self.label_44 = QtGui.QLabel(self.hum_details_ch)
        self.label_44.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.taurusLabel_27 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_27.setGeometry(QtCore.QRect(80, 70, 51, 17))
        self.taurusLabel_27.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_27.setPrefixText(_fromUtf8(""))
        self.taurusLabel_27.setObjectName(_fromUtf8("taurusLabel_27"))
        self.label_45 = QtGui.QLabel(self.hum_details_ch)
        self.label_45.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.taurusLabel_28 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_28.setGeometry(QtCore.QRect(80, 90, 51, 17))
        self.taurusLabel_28.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_28.setPrefixText(_fromUtf8(""))
        self.taurusLabel_28.setObjectName(_fromUtf8("taurusLabel_28"))
        self.label_46 = QtGui.QLabel(self.hum_details_ch)
        self.label_46.setGeometry(QtCore.QRect(20, 90, 61, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.taurusLabel_29 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_29.setGeometry(QtCore.QRect(80, 110, 51, 17))
        self.taurusLabel_29.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_29.setPrefixText(_fromUtf8(""))
        self.taurusLabel_29.setObjectName(_fromUtf8("taurusLabel_29"))
        self.label_47 = QtGui.QLabel(self.hum_details_ch)
        self.label_47.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.taurusLabel_30 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_30.setGeometry(QtCore.QRect(80, 130, 51, 17))
        self.taurusLabel_30.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_30.setPrefixText(_fromUtf8(""))
        self.taurusLabel_30.setObjectName(_fromUtf8("taurusLabel_30"))
        self.label_48 = QtGui.QLabel(self.hum_details_ch)
        self.label_48.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.taurusLabel_31 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_31.setGeometry(QtCore.QRect(210, 30, 51, 17))
        self.taurusLabel_31.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_31.setPrefixText(_fromUtf8(""))
        self.taurusLabel_31.setObjectName(_fromUtf8("taurusLabel_31"))
        self.label_49 = QtGui.QLabel(self.hum_details_ch)
        self.label_49.setGeometry(QtCore.QRect(150, 30, 61, 16))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.taurusLabel_32 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_32.setGeometry(QtCore.QRect(210, 50, 51, 17))
        self.taurusLabel_32.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_32.setPrefixText(_fromUtf8(""))
        self.taurusLabel_32.setObjectName(_fromUtf8("taurusLabel_32"))
        self.label_50 = QtGui.QLabel(self.hum_details_ch)
        self.label_50.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.taurusLabel_33 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_33.setGeometry(QtCore.QRect(210, 70, 51, 17))
        self.taurusLabel_33.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_33.setPrefixText(_fromUtf8(""))
        self.taurusLabel_33.setObjectName(_fromUtf8("taurusLabel_33"))
        self.label_51 = QtGui.QLabel(self.hum_details_ch)
        self.label_51.setGeometry(QtCore.QRect(150, 70, 61, 16))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.taurusLabel_34 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_34.setGeometry(QtCore.QRect(210, 90, 51, 17))
        self.taurusLabel_34.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_34.setPrefixText(_fromUtf8(""))
        self.taurusLabel_34.setObjectName(_fromUtf8("taurusLabel_34"))
        self.label_52 = QtGui.QLabel(self.hum_details_ch)
        self.label_52.setGeometry(QtCore.QRect(150, 90, 61, 16))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.taurusLabel_35 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_35.setGeometry(QtCore.QRect(210, 110, 51, 17))
        self.taurusLabel_35.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_35.setPrefixText(_fromUtf8(""))
        self.taurusLabel_35.setObjectName(_fromUtf8("taurusLabel_35"))
        self.label_53 = QtGui.QLabel(self.hum_details_ch)
        self.label_53.setGeometry(QtCore.QRect(150, 110, 61, 16))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.taurusLabel_36 = TaurusLabel(self.hum_details_ch)
        self.taurusLabel_36.setGeometry(QtCore.QRect(210, 130, 51, 17))
        self.taurusLabel_36.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_36.setPrefixText(_fromUtf8(""))
        self.taurusLabel_36.setObjectName(_fromUtf8("taurusLabel_36"))
        self.label_54 = QtGui.QLabel(self.hum_details_ch)
        self.label_54.setGeometry(QtCore.QRect(150, 130, 61, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.fire_details_ch = QtGui.QFrame(self.frame_details_ch)
        self.fire_details_ch.setGeometry(QtCore.QRect(180, 0, 91, 121))
        self.fire_details_ch.setFrameShape(QtGui.QFrame.NoFrame)
        self.fire_details_ch.setFrameShadow(QtGui.QFrame.Raised)
        self.fire_details_ch.setObjectName(_fromUtf8("fire_details_ch"))
        self.label_55 = QtGui.QLabel(self.fire_details_ch)
        self.label_55.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.fire_details_ch)
        self.label_56.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.fire_details_ch)
        self.label_57.setGeometry(QtCore.QRect(0, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_58 = QtGui.QLabel(self.fire_details_ch)
        self.label_58.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.taurusLed_5 = TaurusLed(self.fire_details_ch)
        self.taurusLed_5.setGeometry(QtCore.QRect(60, 30, 16, 16))
        self.taurusLed_5.setLedInverted(False)
        self.taurusLed_5.setObjectName(_fromUtf8("taurusLed_5"))
        self.taurusLed_6 = TaurusLed(self.fire_details_ch)
        self.taurusLed_6.setGeometry(QtCore.QRect(60, 50, 16, 16))
        self.taurusLed_6.setLedInverted(False)
        self.taurusLed_6.setObjectName(_fromUtf8("taurusLed_6"))
        self.taurusLed_7 = TaurusLed(self.fire_details_ch)
        self.taurusLed_7.setGeometry(QtCore.QRect(60, 70, 16, 16))
        self.taurusLed_7.setLedInverted(False)
        self.taurusLed_7.setObjectName(_fromUtf8("taurusLed_7"))
        self.taurusLed_8 = TaurusLed(self.fire_details_ch)
        self.taurusLed_8.setGeometry(QtCore.QRect(60, 90, 16, 16))
        self.taurusLed_8.setLedInverted(False)
        self.taurusLed_8.setObjectName(_fromUtf8("taurusLed_8"))
        self.label_59 = QtGui.QLabel(self.fire_details_ch)
        self.label_59.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.datacenter_hu = QtGui.QFrame(self.centralwidget)
        self.datacenter_hu.setGeometry(QtCore.QRect(850, 0, 811, 671))
        self.datacenter_hu.setFrameShape(QtGui.QFrame.Box)
        self.datacenter_hu.setFrameShadow(QtGui.QFrame.Raised)
        self.datacenter_hu.setLineWidth(2)
        self.datacenter_hu.setObjectName(_fromUtf8("datacenter_hu"))
        self.label_63 = QtGui.QLabel(self.datacenter_hu)
        self.label_63.setGeometry(QtCore.QRect(450, 120, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.datacenter_hu)
        self.label_64.setGeometry(QtCore.QRect(450, 170, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.taurusLed_9 = TaurusLed(self.datacenter_hu)
        self.taurusLed_9.setGeometry(QtCore.QRect(580, 110, 31, 31))
        self.taurusLed_9.setLedInverted(False)
        self.taurusLed_9.setObjectName(_fromUtf8("taurusLed_9"))
        self.taurusLed_10 = TaurusLed(self.datacenter_hu)
        self.taurusLed_10.setGeometry(QtCore.QRect(580, 160, 31, 31))
        self.taurusLed_10.setLedInverted(False)
        self.taurusLed_10.setObjectName(_fromUtf8("taurusLed_10"))
        self.label_65 = QtGui.QLabel(self.datacenter_hu)
        self.label_65.setGeometry(QtCore.QRect(450, 210, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.taurusLed_11 = TaurusLed(self.datacenter_hu)
        self.taurusLed_11.setGeometry(QtCore.QRect(580, 200, 31, 31))
        self.taurusLed_11.setLedInverted(False)
        self.taurusLed_11.setObjectName(_fromUtf8("taurusLed_11"))
        self.btn_details_hu = QtGui.QPushButton(self.datacenter_hu)
        self.btn_details_hu.setGeometry(QtCore.QRect(520, 340, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_details_hu.setFont(font)
        self.btn_details_hu.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.btn_details_hu.setCheckable(True)
        self.btn_details_hu.setChecked(True)
        self.btn_details_hu.setAutoDefault(False)
        self.btn_details_hu.setObjectName(_fromUtf8("btn_details_hu"))
        self.label_66 = QtGui.QLabel(self.datacenter_hu)
        self.label_66.setGeometry(QtCore.QRect(270, 20, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setFrameShape(QtGui.QFrame.Box)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.taurusLed_12 = TaurusLed(self.datacenter_hu)
        self.taurusLed_12.setGeometry(QtCore.QRect(580, 250, 31, 31))
        self.taurusLed_12.setLedInverted(False)
        self.taurusLed_12.setObjectName(_fromUtf8("taurusLed_12"))
        self.label_67 = QtGui.QLabel(self.datacenter_hu)
        self.label_67.setGeometry(QtCore.QRect(450, 260, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.qPixmapWidget_5 = QPixmapWidget(self.datacenter_hu)
        self.qPixmapWidget_5.setGeometry(QtCore.QRect(20, 80, 411, 321))
        self.qPixmapWidget_5.setPixmap(QtGui.QPixmap(_fromUtf8("images/cern_hu.jpg")))
        self.qPixmapWidget_5.setAspectRatioMode(QtCore.Qt.IgnoreAspectRatio)
        self.qPixmapWidget_5.setObjectName(_fromUtf8("qPixmapWidget_5"))
        self.label_22 = QtGui.QLabel(self.datacenter_hu)
        self.label_22.setGeometry(QtCore.QRect(630, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.datacenter_hu)
        self.label_23.setGeometry(QtCore.QRect(630, 260, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.datacenter_hu)
        self.label_24.setGeometry(QtCore.QRect(630, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.frame_details_hu = TaurusWidget(self.centralwidget)
        self.frame_details_hu.setGeometry(QtCore.QRect(850, 470, 831, 201))
        self.frame_details_hu.setObjectName(_fromUtf8("frame_details_hu"))
        self.air_details_hu = QtGui.QFrame(self.frame_details_hu)
        self.air_details_hu.setGeometry(QtCore.QRect(10, 0, 171, 121))
        self.air_details_hu.setFrameShape(QtGui.QFrame.NoFrame)
        self.air_details_hu.setFrameShadow(QtGui.QFrame.Raised)
        self.air_details_hu.setObjectName(_fromUtf8("air_details_hu"))
        self.taurusLabel_37 = TaurusLabel(self.air_details_hu)
        self.taurusLabel_37.setGeometry(QtCore.QRect(90, 90, 61, 17))
        self.taurusLabel_37.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_37.setPrefixText(_fromUtf8(""))
        self.taurusLabel_37.setObjectName(_fromUtf8("taurusLabel_37"))
        self.label_68 = QtGui.QLabel(self.air_details_hu)
        self.label_68.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.taurusLabel_38 = TaurusLabel(self.air_details_hu)
        self.taurusLabel_38.setGeometry(QtCore.QRect(90, 60, 61, 17))
        self.taurusLabel_38.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_38.setPrefixText(_fromUtf8(""))
        self.taurusLabel_38.setObjectName(_fromUtf8("taurusLabel_38"))
        self.taurusLabel_39 = TaurusLabel(self.air_details_hu)
        self.taurusLabel_39.setGeometry(QtCore.QRect(90, 30, 61, 17))
        self.taurusLabel_39.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_39.setPrefixText(_fromUtf8(""))
        self.taurusLabel_39.setObjectName(_fromUtf8("taurusLabel_39"))
        self.label_69 = QtGui.QLabel(self.air_details_hu)
        self.label_69.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_70 = QtGui.QLabel(self.air_details_hu)
        self.label_70.setGeometry(QtCore.QRect(20, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_71 = QtGui.QLabel(self.air_details_hu)
        self.label_71.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.temp_details_hu = QtGui.QFrame(self.frame_details_hu)
        self.temp_details_hu.setGeometry(QtCore.QRect(270, 0, 251, 161))
        self.temp_details_hu.setFrameShape(QtGui.QFrame.NoFrame)
        self.temp_details_hu.setFrameShadow(QtGui.QFrame.Raised)
        self.temp_details_hu.setObjectName(_fromUtf8("temp_details_hu"))
        self.label_72 = QtGui.QLabel(self.temp_details_hu)
        self.label_72.setGeometry(QtCore.QRect(50, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_73 = QtGui.QLabel(self.temp_details_hu)
        self.label_73.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.taurusLabel_40 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_40.setGeometry(QtCore.QRect(70, 30, 51, 17))
        self.taurusLabel_40.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_40.setPrefixText(_fromUtf8(""))
        self.taurusLabel_40.setObjectName(_fromUtf8("taurusLabel_40"))
        self.taurusLabel_41 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_41.setGeometry(QtCore.QRect(70, 50, 51, 17))
        self.taurusLabel_41.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_41.setPrefixText(_fromUtf8(""))
        self.taurusLabel_41.setObjectName(_fromUtf8("taurusLabel_41"))
        self.label_74 = QtGui.QLabel(self.temp_details_hu)
        self.label_74.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.taurusLabel_42 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_42.setGeometry(QtCore.QRect(70, 70, 51, 17))
        self.taurusLabel_42.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_42.setPrefixText(_fromUtf8(""))
        self.taurusLabel_42.setObjectName(_fromUtf8("taurusLabel_42"))
        self.label_75 = QtGui.QLabel(self.temp_details_hu)
        self.label_75.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.taurusLabel_43 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_43.setGeometry(QtCore.QRect(70, 90, 51, 17))
        self.taurusLabel_43.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_43.setPrefixText(_fromUtf8(""))
        self.taurusLabel_43.setObjectName(_fromUtf8("taurusLabel_43"))
        self.label_76 = QtGui.QLabel(self.temp_details_hu)
        self.label_76.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.taurusLabel_44 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_44.setGeometry(QtCore.QRect(70, 110, 51, 17))
        self.taurusLabel_44.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_44.setPrefixText(_fromUtf8(""))
        self.taurusLabel_44.setObjectName(_fromUtf8("taurusLabel_44"))
        self.label_77 = QtGui.QLabel(self.temp_details_hu)
        self.label_77.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.taurusLabel_45 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_45.setGeometry(QtCore.QRect(70, 130, 51, 17))
        self.taurusLabel_45.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_45.setPrefixText(_fromUtf8(""))
        self.taurusLabel_45.setObjectName(_fromUtf8("taurusLabel_45"))
        self.label_78 = QtGui.QLabel(self.temp_details_hu)
        self.label_78.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.taurusLabel_46 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_46.setGeometry(QtCore.QRect(190, 30, 51, 17))
        self.taurusLabel_46.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_46.setPrefixText(_fromUtf8(""))
        self.taurusLabel_46.setObjectName(_fromUtf8("taurusLabel_46"))
        self.label_79 = QtGui.QLabel(self.temp_details_hu)
        self.label_79.setGeometry(QtCore.QRect(130, 30, 61, 16))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.taurusLabel_47 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_47.setGeometry(QtCore.QRect(190, 50, 51, 17))
        self.taurusLabel_47.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_47.setPrefixText(_fromUtf8(""))
        self.taurusLabel_47.setObjectName(_fromUtf8("taurusLabel_47"))
        self.label_80 = QtGui.QLabel(self.temp_details_hu)
        self.label_80.setGeometry(QtCore.QRect(130, 50, 61, 16))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.taurusLabel_48 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_48.setGeometry(QtCore.QRect(190, 70, 51, 17))
        self.taurusLabel_48.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_48.setPrefixText(_fromUtf8(""))
        self.taurusLabel_48.setObjectName(_fromUtf8("taurusLabel_48"))
        self.label_81 = QtGui.QLabel(self.temp_details_hu)
        self.label_81.setGeometry(QtCore.QRect(130, 70, 61, 16))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.taurusLabel_49 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_49.setGeometry(QtCore.QRect(190, 90, 51, 17))
        self.taurusLabel_49.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_49.setPrefixText(_fromUtf8(""))
        self.taurusLabel_49.setObjectName(_fromUtf8("taurusLabel_49"))
        self.label_82 = QtGui.QLabel(self.temp_details_hu)
        self.label_82.setGeometry(QtCore.QRect(130, 90, 61, 16))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.taurusLabel_50 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_50.setGeometry(QtCore.QRect(190, 110, 51, 17))
        self.taurusLabel_50.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_50.setPrefixText(_fromUtf8(""))
        self.taurusLabel_50.setObjectName(_fromUtf8("taurusLabel_50"))
        self.label_83 = QtGui.QLabel(self.temp_details_hu)
        self.label_83.setGeometry(QtCore.QRect(130, 110, 61, 16))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.taurusLabel_51 = TaurusLabel(self.temp_details_hu)
        self.taurusLabel_51.setGeometry(QtCore.QRect(190, 130, 51, 17))
        self.taurusLabel_51.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_51.setPrefixText(_fromUtf8(""))
        self.taurusLabel_51.setObjectName(_fromUtf8("taurusLabel_51"))
        self.label_84 = QtGui.QLabel(self.temp_details_hu)
        self.label_84.setGeometry(QtCore.QRect(130, 130, 61, 16))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.hum_details_hu = QtGui.QFrame(self.frame_details_hu)
        self.hum_details_hu.setGeometry(QtCore.QRect(520, 0, 271, 191))
        self.hum_details_hu.setFrameShape(QtGui.QFrame.NoFrame)
        self.hum_details_hu.setFrameShadow(QtGui.QFrame.Raised)
        self.hum_details_hu.setObjectName(_fromUtf8("hum_details_hu"))
        self.label_85 = QtGui.QLabel(self.hum_details_hu)
        self.label_85.setGeometry(QtCore.QRect(70, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_86 = QtGui.QLabel(self.hum_details_hu)
        self.label_86.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.taurusLabel_52 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_52.setGeometry(QtCore.QRect(80, 30, 51, 17))
        self.taurusLabel_52.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_52.setPrefixText(_fromUtf8(""))
        self.taurusLabel_52.setObjectName(_fromUtf8("taurusLabel_52"))
        self.taurusLabel_53 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_53.setGeometry(QtCore.QRect(80, 50, 51, 17))
        self.taurusLabel_53.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_53.setPrefixText(_fromUtf8(""))
        self.taurusLabel_53.setObjectName(_fromUtf8("taurusLabel_53"))
        self.label_87 = QtGui.QLabel(self.hum_details_hu)
        self.label_87.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.taurusLabel_54 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_54.setGeometry(QtCore.QRect(80, 70, 51, 17))
        self.taurusLabel_54.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_54.setPrefixText(_fromUtf8(""))
        self.taurusLabel_54.setObjectName(_fromUtf8("taurusLabel_54"))
        self.label_88 = QtGui.QLabel(self.hum_details_hu)
        self.label_88.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.taurusLabel_55 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_55.setGeometry(QtCore.QRect(80, 90, 51, 17))
        self.taurusLabel_55.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_55.setPrefixText(_fromUtf8(""))
        self.taurusLabel_55.setObjectName(_fromUtf8("taurusLabel_55"))
        self.label_89 = QtGui.QLabel(self.hum_details_hu)
        self.label_89.setGeometry(QtCore.QRect(20, 90, 61, 16))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.taurusLabel_56 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_56.setGeometry(QtCore.QRect(80, 110, 51, 17))
        self.taurusLabel_56.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_56.setPrefixText(_fromUtf8(""))
        self.taurusLabel_56.setObjectName(_fromUtf8("taurusLabel_56"))
        self.label_90 = QtGui.QLabel(self.hum_details_hu)
        self.label_90.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.taurusLabel_57 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_57.setGeometry(QtCore.QRect(80, 130, 51, 17))
        self.taurusLabel_57.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_57.setPrefixText(_fromUtf8(""))
        self.taurusLabel_57.setObjectName(_fromUtf8("taurusLabel_57"))
        self.label_91 = QtGui.QLabel(self.hum_details_hu)
        self.label_91.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.taurusLabel_58 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_58.setGeometry(QtCore.QRect(210, 30, 51, 17))
        self.taurusLabel_58.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_58.setPrefixText(_fromUtf8(""))
        self.taurusLabel_58.setObjectName(_fromUtf8("taurusLabel_58"))
        self.label_92 = QtGui.QLabel(self.hum_details_hu)
        self.label_92.setGeometry(QtCore.QRect(150, 30, 61, 16))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.taurusLabel_59 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_59.setGeometry(QtCore.QRect(210, 50, 51, 17))
        self.taurusLabel_59.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_59.setPrefixText(_fromUtf8(""))
        self.taurusLabel_59.setObjectName(_fromUtf8("taurusLabel_59"))
        self.label_93 = QtGui.QLabel(self.hum_details_hu)
        self.label_93.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.taurusLabel_60 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_60.setGeometry(QtCore.QRect(210, 70, 51, 17))
        self.taurusLabel_60.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_60.setPrefixText(_fromUtf8(""))
        self.taurusLabel_60.setObjectName(_fromUtf8("taurusLabel_60"))
        self.label_94 = QtGui.QLabel(self.hum_details_hu)
        self.label_94.setGeometry(QtCore.QRect(150, 70, 61, 16))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.taurusLabel_61 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_61.setGeometry(QtCore.QRect(210, 90, 51, 17))
        self.taurusLabel_61.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_61.setPrefixText(_fromUtf8(""))
        self.taurusLabel_61.setObjectName(_fromUtf8("taurusLabel_61"))
        self.label_95 = QtGui.QLabel(self.hum_details_hu)
        self.label_95.setGeometry(QtCore.QRect(150, 90, 61, 16))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.taurusLabel_62 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_62.setGeometry(QtCore.QRect(210, 110, 51, 17))
        self.taurusLabel_62.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_62.setPrefixText(_fromUtf8(""))
        self.taurusLabel_62.setObjectName(_fromUtf8("taurusLabel_62"))
        self.label_96 = QtGui.QLabel(self.hum_details_hu)
        self.label_96.setGeometry(QtCore.QRect(150, 110, 61, 16))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.taurusLabel_63 = TaurusLabel(self.hum_details_hu)
        self.taurusLabel_63.setGeometry(QtCore.QRect(210, 130, 51, 17))
        self.taurusLabel_63.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_63.setPrefixText(_fromUtf8(""))
        self.taurusLabel_63.setObjectName(_fromUtf8("taurusLabel_63"))
        self.label_97 = QtGui.QLabel(self.hum_details_hu)
        self.label_97.setGeometry(QtCore.QRect(150, 130, 61, 16))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.fire_details_hu = QtGui.QFrame(self.frame_details_hu)
        self.fire_details_hu.setGeometry(QtCore.QRect(180, 0, 91, 121))
        self.fire_details_hu.setFrameShape(QtGui.QFrame.NoFrame)
        self.fire_details_hu.setFrameShadow(QtGui.QFrame.Raised)
        self.fire_details_hu.setObjectName(_fromUtf8("fire_details_hu"))
        self.label_98 = QtGui.QLabel(self.fire_details_hu)
        self.label_98.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.fire_details_hu)
        self.label_99.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.fire_details_hu)
        self.label_100.setGeometry(QtCore.QRect(0, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_100.setFont(font)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.label_101 = QtGui.QLabel(self.fire_details_hu)
        self.label_101.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.taurusLed_13 = TaurusLed(self.fire_details_hu)
        self.taurusLed_13.setGeometry(QtCore.QRect(60, 30, 16, 16))
        self.taurusLed_13.setLedInverted(False)
        self.taurusLed_13.setObjectName(_fromUtf8("taurusLed_13"))
        self.taurusLed_14 = TaurusLed(self.fire_details_hu)
        self.taurusLed_14.setGeometry(QtCore.QRect(60, 50, 16, 16))
        self.taurusLed_14.setLedInverted(False)
        self.taurusLed_14.setObjectName(_fromUtf8("taurusLed_14"))
        self.taurusLed_15 = TaurusLed(self.fire_details_hu)
        self.taurusLed_15.setGeometry(QtCore.QRect(60, 70, 16, 16))
        self.taurusLed_15.setLedInverted(False)
        self.taurusLed_15.setObjectName(_fromUtf8("taurusLed_15"))
        self.taurusLed_16 = TaurusLed(self.fire_details_hu)
        self.taurusLed_16.setGeometry(QtCore.QRect(60, 90, 16, 16))
        self.taurusLed_16.setLedInverted(False)
        self.taurusLed_16.setObjectName(_fromUtf8("taurusLed_16"))
        self.label_102 = QtGui.QLabel(self.fire_details_hu)
        self.label_102.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.frame = QtGui.QFrame(self.frame_details_hu)
        self.frame.setGeometry(QtCore.QRect(10, 120, 261, 71))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.taurusLabel = TaurusLabel(self.frame)
        self.taurusLabel.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.taurusLabel.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel.setObjectName(_fromUtf8("taurusLabel"))
        self.taurusLabel_2 = TaurusLabel(self.frame)
        self.taurusLabel_2.setGeometry(QtCore.QRect(90, 50, 51, 17))
        self.taurusLabel_2.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_2.setObjectName(_fromUtf8("taurusLabel_2"))
        self.taurusLabel_3 = TaurusLabel(self.frame)
        self.taurusLabel_3.setGeometry(QtCore.QRect(180, 50, 51, 17))
        self.taurusLabel_3.setStyleSheet(_fromUtf8("background-color: rgb(198, 255, 212);"))
        self.taurusLabel_3.setObjectName(_fromUtf8("taurusLabel_3"))
        self.label_103 = QtGui.QLabel(self.frame)
        self.label_103.setGeometry(QtCore.QRect(80, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_103.setFont(font)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 30, 57, 15))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(180, 30, 57, 15))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1703, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btn_details_ch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_details_ch.setVisible)
        QtCore.QObject.connect(self.btn_details_hu, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_details_hu.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        MainWindow.setToolTip(_translate("MainWindow", "Edit the value to change fan speed", None))
        self.label.setText(_translate("MainWindow", "FAN_00", None))
        self.taurusLabelEditRW.setToolTip(_translate("MainWindow", "Edit the value to change fan speed", None))
        self.taurusLabelEditRW.setModel(_translate("MainWindow", "epfl/vds/1/fan_00", None))
        self.label_15.setText(_translate("MainWindow", "Speed at", None))
        self.label_16.setText(_translate("MainWindow", "%", None))
        self.label_2.setText(_translate("MainWindow", "FAN_01", None))
        self.label_17.setText(_translate("MainWindow", "%", None))
        self.taurusLabelEditRW_2.setToolTip(_translate("MainWindow", "Edit the value to change fan speed", None))
        self.taurusLabelEditRW_2.setModel(_translate("MainWindow", "epfl/vds/1/fan_01", None))
        self.label_18.setText(_translate("MainWindow", "Speed at", None))
        self.label_3.setText(_translate("MainWindow", "FAN_02", None))
        self.label_20.setText(_translate("MainWindow", "Speed at", None))
        self.label_19.setText(_translate("MainWindow", "%", None))
        self.taurusLabelEditRW_3.setToolTip(_translate("MainWindow", "Edit the value to change fan speed", None))
        self.taurusLabelEditRW_3.setModel(_translate("MainWindow", "epfl/vds/2/fan_02", None))
        self.taurusCommandButton_7.setText(_translate("MainWindow", "100 %", None))
        self.taurusCommandButton_7.setModel(_translate("MainWindow", "epfl/vds/1", None))
        self.taurusCommandButton_7.setCommand(_translate("MainWindow", "start", None))
        self.taurusCommandButton_8.setText(_translate("MainWindow", "0 %", None))
        self.taurusCommandButton_8.setModel(_translate("MainWindow", "epfl/vds/1", None))
        self.taurusCommandButton_8.setCommand(_translate("MainWindow", "stop", None))
        self.label_4.setText(_translate("MainWindow", "Ventilation system", None))
        self.label_11.setText(_translate("MainWindow", "Temperature: ", None))
        self.label_12.setText(_translate("MainWindow", "Humidity:", None))
        self.taurusLed_3.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_3.setModel(_translate("MainWindow", "epfl/vds/2/temp_alarm", None))
        self.taurusLed_3.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_3.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_2.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_2.setModel(_translate("MainWindow", "epfl/vds/1/hum_alarm", None))
        self.taurusLed_2.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_2.setOffColor(_translate("MainWindow", "green", None))
        self.label_13.setText(_translate("MainWindow", "Fire:", None))
        self.taurusLed_4.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_4.setModel(_translate("MainWindow", "epfl/vds/2/fire_alarm", None))
        self.taurusLed_4.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_4.setOffColor(_translate("MainWindow", "green", None))
        self.btn_details_ch.setText(_translate("MainWindow", "Sensors details", None))
        self.label_14.setText(_translate("MainWindow", "Swiss datacenter", None))
        self.taurusLed.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed.setModel(_translate("MainWindow", "epfl/vds/1/air_flow_alarm", None))
        self.taurusLed.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed.setOffColor(_translate("MainWindow", "green", None))
        self.label_9.setText(_translate("MainWindow", "Air flow:", None))
        self.label_8.setText(_translate("MainWindow", "(18°C - 27 °C)", None))
        self.label_10.setText(_translate("MainWindow", "(20% -80%)", None))
        self.label_21.setText(_translate("MainWindow", "(66% - 100%)", None))
        self.taurusLabel_10.setModel(_translate("MainWindow", "epfl/vds/2/air_flow_02", None))
        self.taurusLabel_10.setSuffixText(_translate("MainWindow", "%", None))
        self.label_26.setText(_translate("MainWindow", "air_flow_00:", None))
        self.taurusLabel_11.setModel(_translate("MainWindow", "epfl/vds/1/air_flow_01", None))
        self.taurusLabel_11.setSuffixText(_translate("MainWindow", "%", None))
        self.taurusLabel_12.setModel(_translate("MainWindow", "epfl/vds/2/air_flow_00", None))
        self.taurusLabel_12.setSuffixText(_translate("MainWindow", "%", None))
        self.label_25.setText(_translate("MainWindow", "air_flow_02:", None))
        self.label_27.setText(_translate("MainWindow", "Air flow sensors:", None))
        self.label_28.setText(_translate("MainWindow", "air_flow_01:", None))
        self.label_29.setText(_translate("MainWindow", "Temperature sensors:", None))
        self.label_30.setText(_translate("MainWindow", "temp_00:", None))
        self.taurusLabel_13.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_13.setModel(_translate("MainWindow", "epfl/vds/2/temp_00", None))
        self.taurusLabel_13.setSuffixText(_translate("MainWindow", "C", None))
        self.taurusLabel_14.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_14.setModel(_translate("MainWindow", "epfl/vds/1/temp_01", None))
        self.taurusLabel_14.setSuffixText(_translate("MainWindow", "C", None))
        self.label_31.setText(_translate("MainWindow", "temp_01:", None))
        self.taurusLabel_15.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_15.setModel(_translate("MainWindow", "epfl/vds/2/temp_02", None))
        self.taurusLabel_15.setSuffixText(_translate("MainWindow", "C", None))
        self.label_32.setText(_translate("MainWindow", "temp_02:", None))
        self.taurusLabel_16.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_16.setModel(_translate("MainWindow", "epfl/vds/1/temp_03", None))
        self.taurusLabel_16.setSuffixText(_translate("MainWindow", "C", None))
        self.label_33.setText(_translate("MainWindow", "temp_03:", None))
        self.taurusLabel_17.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_17.setModel(_translate("MainWindow", "epfl/vds/2/temp_04", None))
        self.taurusLabel_17.setSuffixText(_translate("MainWindow", "C", None))
        self.label_34.setText(_translate("MainWindow", "temp_04:", None))
        self.taurusLabel_18.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_18.setModel(_translate("MainWindow", "epfl/vds/1/temp_05", None))
        self.taurusLabel_18.setSuffixText(_translate("MainWindow", "C", None))
        self.label_35.setText(_translate("MainWindow", "temp_05:", None))
        self.taurusLabel_19.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_19.setModel(_translate("MainWindow", "epfl/vds/2/temp_06", None))
        self.taurusLabel_19.setSuffixText(_translate("MainWindow", "C", None))
        self.label_36.setText(_translate("MainWindow", "temp_06:", None))
        self.taurusLabel_20.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_20.setModel(_translate("MainWindow", "epfl/vds/1/temp_07", None))
        self.taurusLabel_20.setSuffixText(_translate("MainWindow", "C", None))
        self.label_37.setText(_translate("MainWindow", "temp_07:", None))
        self.taurusLabel_21.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_21.setModel(_translate("MainWindow", "epfl/vds/2/temp_08", None))
        self.taurusLabel_21.setSuffixText(_translate("MainWindow", "C", None))
        self.label_38.setText(_translate("MainWindow", "temp_08:", None))
        self.taurusLabel_22.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_22.setModel(_translate("MainWindow", "epfl/vds/1/temp_09", None))
        self.taurusLabel_22.setSuffixText(_translate("MainWindow", "C", None))
        self.label_39.setText(_translate("MainWindow", "temp_09:", None))
        self.taurusLabel_23.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_23.setModel(_translate("MainWindow", "epfl/vds/2/temp_10", None))
        self.taurusLabel_23.setSuffixText(_translate("MainWindow", "C", None))
        self.label_40.setText(_translate("MainWindow", "temp_10:", None))
        self.taurusLabel_24.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_24.setModel(_translate("MainWindow", "epfl/vds/1/temp_11", None))
        self.taurusLabel_24.setSuffixText(_translate("MainWindow", "C", None))
        self.label_41.setText(_translate("MainWindow", "temp_11:", None))
        self.label_42.setText(_translate("MainWindow", "Humidity sensors:", None))
        self.label_43.setText(_translate("MainWindow", "hum_00:", None))
        self.taurusLabel_25.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_25.setModel(_translate("MainWindow", "epfl/vds/2/hum_00", None))
        self.taurusLabel_25.setSuffixText(_translate("MainWindow", "%", None))
        self.taurusLabel_26.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_26.setModel(_translate("MainWindow", "epfl/vds/1/hum_01", None))
        self.taurusLabel_26.setSuffixText(_translate("MainWindow", "%", None))
        self.label_44.setText(_translate("MainWindow", "hum_01:", None))
        self.taurusLabel_27.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_27.setModel(_translate("MainWindow", "epfl/vds/2/hum_02", None))
        self.taurusLabel_27.setSuffixText(_translate("MainWindow", "%", None))
        self.label_45.setText(_translate("MainWindow", "hum_02:", None))
        self.taurusLabel_28.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_28.setModel(_translate("MainWindow", "epfl/vds/1/hum_03", None))
        self.taurusLabel_28.setSuffixText(_translate("MainWindow", "%", None))
        self.label_46.setText(_translate("MainWindow", "hum_03:", None))
        self.taurusLabel_29.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_29.setModel(_translate("MainWindow", "epfl/vds/2/hum_04", None))
        self.taurusLabel_29.setSuffixText(_translate("MainWindow", "%", None))
        self.label_47.setText(_translate("MainWindow", "hum_04:", None))
        self.taurusLabel_30.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_30.setModel(_translate("MainWindow", "epfl/vds/1/hum_05", None))
        self.taurusLabel_30.setSuffixText(_translate("MainWindow", "%", None))
        self.label_48.setText(_translate("MainWindow", "hum_05:", None))
        self.taurusLabel_31.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_31.setModel(_translate("MainWindow", "epfl/vds/2/hum_06", None))
        self.taurusLabel_31.setSuffixText(_translate("MainWindow", "%", None))
        self.label_49.setText(_translate("MainWindow", "hum_06:", None))
        self.taurusLabel_32.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_32.setModel(_translate("MainWindow", "epfl/vds/1/hum_07", None))
        self.taurusLabel_32.setSuffixText(_translate("MainWindow", "%", None))
        self.label_50.setText(_translate("MainWindow", "hum_07:", None))
        self.taurusLabel_33.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_33.setModel(_translate("MainWindow", "epfl/vds/2/hum_08", None))
        self.taurusLabel_33.setSuffixText(_translate("MainWindow", "%", None))
        self.label_51.setText(_translate("MainWindow", "hum_08:", None))
        self.taurusLabel_34.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_34.setModel(_translate("MainWindow", "epfl/vds/1/hum_09", None))
        self.taurusLabel_34.setSuffixText(_translate("MainWindow", "%", None))
        self.label_52.setText(_translate("MainWindow", "hum_09:", None))
        self.taurusLabel_35.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_35.setModel(_translate("MainWindow", "epfl/vds/2/hum_10", None))
        self.taurusLabel_35.setSuffixText(_translate("MainWindow", "%", None))
        self.label_53.setText(_translate("MainWindow", "hum_10:", None))
        self.taurusLabel_36.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_36.setModel(_translate("MainWindow", "epfl/vds/1/hum_11", None))
        self.taurusLabel_36.setSuffixText(_translate("MainWindow", "%", None))
        self.label_54.setText(_translate("MainWindow", "hum_11:", None))
        self.label_55.setText(_translate("MainWindow", "fire_00:", None))
        self.label_56.setText(_translate("MainWindow", "fire_02:", None))
        self.label_57.setText(_translate("MainWindow", "Fire sensors:", None))
        self.label_58.setText(_translate("MainWindow", "fire_01:", None))
        self.taurusLed_5.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_5.setModel(_translate("MainWindow", "epfl/vds/1/fire_00", None))
        self.taurusLed_5.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_5.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_6.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_6.setModel(_translate("MainWindow", "epfl/vds/2/fire_01", None))
        self.taurusLed_6.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_6.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_7.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_7.setModel(_translate("MainWindow", "epfl/vds/2/fire_02", None))
        self.taurusLed_7.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_7.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_8.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_8.setModel(_translate("MainWindow", "epfl/vds/1/fire_03", None))
        self.taurusLed_8.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_8.setOffColor(_translate("MainWindow", "green", None))
        self.label_59.setText(_translate("MainWindow", "fire_03:", None))
        self.label_63.setText(_translate("MainWindow", "Temperature: ", None))
        self.label_64.setText(_translate("MainWindow", "Humidity:", None))
        self.taurusLed_9.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_9.setModel(_translate("MainWindow", "epfl/vds/3/temp_alarm", None))
        self.taurusLed_9.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_9.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_10.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_10.setModel(_translate("MainWindow", "epfl/vds/3/hum_alarm", None))
        self.taurusLed_10.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_10.setOffColor(_translate("MainWindow", "green", None))
        self.label_65.setText(_translate("MainWindow", "Fire:", None))
        self.taurusLed_11.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_11.setModel(_translate("MainWindow", "epfl/vds/3/fire_alarm", None))
        self.taurusLed_11.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_11.setOffColor(_translate("MainWindow", "green", None))
        self.btn_details_hu.setText(_translate("MainWindow", "Sensors details", None))
        self.label_66.setText(_translate("MainWindow", "Hungarian datacenter", None))
        self.taurusLed_12.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_12.setModel(_translate("MainWindow", "epfl/vds/3/air_flow_alarm", None))
        self.taurusLed_12.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_12.setOffColor(_translate("MainWindow", "green", None))
        self.label_67.setText(_translate("MainWindow", "Air flow:", None))
        self.label_22.setText(_translate("MainWindow", "(20% -80%)", None))
        self.label_23.setText(_translate("MainWindow", "(66% - 100%)", None))
        self.label_24.setText(_translate("MainWindow", "(18°C - 27 °C)", None))
        self.taurusLabel_37.setModel(_translate("MainWindow", "epfl/vds/3/air_flow_02", None))
        self.taurusLabel_37.setSuffixText(_translate("MainWindow", "%", None))
        self.label_68.setText(_translate("MainWindow", "air_flow_00:", None))
        self.taurusLabel_38.setModel(_translate("MainWindow", "epfl/vds/3/air_flow_01", None))
        self.taurusLabel_38.setSuffixText(_translate("MainWindow", "%", None))
        self.taurusLabel_39.setModel(_translate("MainWindow", "epfl/vds/3/air_flow_00", None))
        self.taurusLabel_39.setSuffixText(_translate("MainWindow", "%", None))
        self.label_69.setText(_translate("MainWindow", "air_flow_02:", None))
        self.label_70.setText(_translate("MainWindow", "Air flow sensors:", None))
        self.label_71.setText(_translate("MainWindow", "air_flow_01:", None))
        self.label_72.setText(_translate("MainWindow", "Temperature sensors:", None))
        self.label_73.setText(_translate("MainWindow", "temp_00:", None))
        self.taurusLabel_40.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_40.setModel(_translate("MainWindow", "epfl/vds/3/temp_00", None))
        self.taurusLabel_40.setSuffixText(_translate("MainWindow", "C", None))
        self.taurusLabel_41.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_41.setModel(_translate("MainWindow", "epfl/vds/3/temp_01", None))
        self.taurusLabel_41.setSuffixText(_translate("MainWindow", "C", None))
        self.label_74.setText(_translate("MainWindow", "temp_01:", None))
        self.taurusLabel_42.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_42.setModel(_translate("MainWindow", "epfl/vds/3/temp_02", None))
        self.taurusLabel_42.setSuffixText(_translate("MainWindow", "C", None))
        self.label_75.setText(_translate("MainWindow", "temp_02:", None))
        self.taurusLabel_43.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_43.setModel(_translate("MainWindow", "epfl/vds/3/temp_03", None))
        self.taurusLabel_43.setSuffixText(_translate("MainWindow", "C", None))
        self.label_76.setText(_translate("MainWindow", "temp_03:", None))
        self.taurusLabel_44.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_44.setModel(_translate("MainWindow", "epfl/vds/3/temp_04", None))
        self.taurusLabel_44.setSuffixText(_translate("MainWindow", "C", None))
        self.label_77.setText(_translate("MainWindow", "temp_04:", None))
        self.taurusLabel_45.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_45.setModel(_translate("MainWindow", "epfl/vds/3/temp_05", None))
        self.taurusLabel_45.setSuffixText(_translate("MainWindow", "C", None))
        self.label_78.setText(_translate("MainWindow", "temp_05:", None))
        self.taurusLabel_46.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_46.setModel(_translate("MainWindow", "epfl/vds/3/temp_06", None))
        self.taurusLabel_46.setSuffixText(_translate("MainWindow", "C", None))
        self.label_79.setText(_translate("MainWindow", "temp_06:", None))
        self.taurusLabel_47.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_47.setModel(_translate("MainWindow", "epfl/vds/3/temp_07", None))
        self.taurusLabel_47.setSuffixText(_translate("MainWindow", "C", None))
        self.label_80.setText(_translate("MainWindow", "temp_07:", None))
        self.taurusLabel_48.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_48.setModel(_translate("MainWindow", "epfl/vds/3/temp_08", None))
        self.taurusLabel_48.setSuffixText(_translate("MainWindow", "C", None))
        self.label_81.setText(_translate("MainWindow", "temp_08:", None))
        self.taurusLabel_49.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_49.setModel(_translate("MainWindow", "epfl/vds/3/temp_09", None))
        self.taurusLabel_49.setSuffixText(_translate("MainWindow", "C", None))
        self.label_82.setText(_translate("MainWindow", "temp_09:", None))
        self.taurusLabel_50.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_50.setModel(_translate("MainWindow", "epfl/vds/3/temp_10", None))
        self.taurusLabel_50.setSuffixText(_translate("MainWindow", "C", None))
        self.label_83.setText(_translate("MainWindow", "temp_10:", None))
        self.taurusLabel_51.setText(_translate("MainWindow", " 99.99C", None))
        self.taurusLabel_51.setModel(_translate("MainWindow", "epfl/vds/3/temp_11", None))
        self.taurusLabel_51.setSuffixText(_translate("MainWindow", "C", None))
        self.label_84.setText(_translate("MainWindow", "temp_11:", None))
        self.label_85.setText(_translate("MainWindow", "Humidity sensors:", None))
        self.label_86.setText(_translate("MainWindow", "hum_00:", None))
        self.taurusLabel_52.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_52.setModel(_translate("MainWindow", "epfl/vds/3/hum_00", None))
        self.taurusLabel_52.setSuffixText(_translate("MainWindow", "%", None))
        self.taurusLabel_53.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_53.setModel(_translate("MainWindow", "epfl/vds/3/hum_01", None))
        self.taurusLabel_53.setSuffixText(_translate("MainWindow", "%", None))
        self.label_87.setText(_translate("MainWindow", "hum_01:", None))
        self.taurusLabel_54.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_54.setModel(_translate("MainWindow", "epfl/vds/3/hum_02", None))
        self.taurusLabel_54.setSuffixText(_translate("MainWindow", "%", None))
        self.label_88.setText(_translate("MainWindow", "hum_02:", None))
        self.taurusLabel_55.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_55.setModel(_translate("MainWindow", "epfl/vds/3/hum_03", None))
        self.taurusLabel_55.setSuffixText(_translate("MainWindow", "%", None))
        self.label_89.setText(_translate("MainWindow", "hum_03:", None))
        self.taurusLabel_56.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_56.setModel(_translate("MainWindow", "epfl/vds/3/hum_04", None))
        self.taurusLabel_56.setSuffixText(_translate("MainWindow", "%", None))
        self.label_90.setText(_translate("MainWindow", "hum_04:", None))
        self.taurusLabel_57.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_57.setModel(_translate("MainWindow", "epfl/vds/3/hum_05", None))
        self.taurusLabel_57.setSuffixText(_translate("MainWindow", "%", None))
        self.label_91.setText(_translate("MainWindow", "hum_05:", None))
        self.taurusLabel_58.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_58.setModel(_translate("MainWindow", "epfl/vds/3/hum_06", None))
        self.taurusLabel_58.setSuffixText(_translate("MainWindow", "%", None))
        self.label_92.setText(_translate("MainWindow", "hum_06:", None))
        self.taurusLabel_59.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_59.setModel(_translate("MainWindow", "epfl/vds/3/hum_07", None))
        self.taurusLabel_59.setSuffixText(_translate("MainWindow", "%", None))
        self.label_93.setText(_translate("MainWindow", "hum_07:", None))
        self.taurusLabel_60.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_60.setModel(_translate("MainWindow", "epfl/vds/3/hum_08", None))
        self.taurusLabel_60.setSuffixText(_translate("MainWindow", "%", None))
        self.label_94.setText(_translate("MainWindow", "hum_08:", None))
        self.taurusLabel_61.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_61.setModel(_translate("MainWindow", "epfl/vds/3/hum_09", None))
        self.taurusLabel_61.setSuffixText(_translate("MainWindow", "%", None))
        self.label_95.setText(_translate("MainWindow", "hum_09:", None))
        self.taurusLabel_62.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_62.setModel(_translate("MainWindow", "epfl/vds/3/hum_10", None))
        self.taurusLabel_62.setSuffixText(_translate("MainWindow", "%", None))
        self.label_96.setText(_translate("MainWindow", "hum_10:", None))
        self.taurusLabel_63.setText(_translate("MainWindow", " 99.99%", None))
        self.taurusLabel_63.setModel(_translate("MainWindow", "epfl/vds/3/hum_11", None))
        self.taurusLabel_63.setSuffixText(_translate("MainWindow", "%", None))
        self.label_97.setText(_translate("MainWindow", "hum_11:", None))
        self.label_98.setText(_translate("MainWindow", "fire_00:", None))
        self.label_99.setText(_translate("MainWindow", "fire_02:", None))
        self.label_100.setText(_translate("MainWindow", "Fire sensors:", None))
        self.label_101.setText(_translate("MainWindow", "fire_01:", None))
        self.taurusLed_13.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_13.setModel(_translate("MainWindow", "epfl/vds/3/fire_00", None))
        self.taurusLed_13.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_13.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_14.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_14.setModel(_translate("MainWindow", "epfl/vds/3/fire_01", None))
        self.taurusLed_14.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_14.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_15.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_15.setModel(_translate("MainWindow", "epfl/vds/3/fire_02", None))
        self.taurusLed_15.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_15.setOffColor(_translate("MainWindow", "green", None))
        self.taurusLed_16.setProperty("ledPattern", _translate("MainWindow", ":leds/images256/led_{color}_on.png", None))
        self.taurusLed_16.setModel(_translate("MainWindow", "epfl/vds/3/fire_03", None))
        self.taurusLed_16.setOnColor(_translate("MainWindow", "red", None))
        self.taurusLed_16.setOffColor(_translate("MainWindow", "green", None))
        self.label_102.setText(_translate("MainWindow", "fire_03:", None))
        self.taurusLabel.setModel(_translate("MainWindow", "epfl/vds/3/fan_00", None))
        self.taurusLabel.setSuffixText(_translate("MainWindow", "%", None))
        self.taurusLabel_2.setModel(_translate("MainWindow", "epfl/vds/3/fan_01", None))
        self.taurusLabel_2.setSuffixText(_translate("MainWindow", "%", None))
        self.taurusLabel_3.setModel(_translate("MainWindow", "epfl/vds/3/fan_02", None))
        self.taurusLabel_3.setSuffixText(_translate("MainWindow", "%", None))
        self.label_103.setText(_translate("MainWindow", "Fan sensors:", None))
        self.label_5.setText(_translate("MainWindow", "fan_00:", None))
        self.label_6.setText(_translate("MainWindow", "fan_01:", None))
        self.label_7.setText(_translate("MainWindow", "fan_02:", None))

from taurus.qt.qtgui.display import TaurusLed, TaurusLabel, QPixmapWidget
from taurus.qt.qtgui.container import TaurusWidget
from taurus.qt.qtgui.button import TaurusCommandButton
from taurus.qt.qtgui.compact import TaurusLabelEditRW

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

